# This file has been autogenerated in 'extras/ModuleMaintenance.R'. Do not change by hand. 
library(CohortMethod)

createCohortMethodModuleSpecifications <- function(cmAnalysisList,
                                                   targetComparatorOutcomesList,
                                                   analysesToExclude = NULL,
                                                   refitPsForEveryOutcome = FALSE,
                                                   refitPsForEveryStudyPopulation = TRUE,
                                                   cmDiagnosticThresholds = createCmDiagnosticThresholds()) {
  analysis <- list()
  for (name in names(formals(createCohortMethodModuleSpecifications))) {
    analysis[[name]] <- get(name)
  }

  specifications <- list(module = "CohortMethodModule",
                         version = "0.2.0-5",
                         remoteRepo = "github.com",
                         remoteUsername = "ohdsi",
                         settings = analysis)
  class(specifications) <- c("CohortMethodModuleSpecifications", "ModuleSpecifications")
  return(specifications)
}
